[project]
name = "water-quality-early-warning-system"
version = "0.1.0"
description = "Water Quality Early Warning System"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.4.2",
    "matplotlib>=3.10.1",
    "scikit-learn>=1.6.1",
    "streamlit>=1.44.1",
]
